source 'https://rubygems.org'

ruby '2.1.5'
gem 'activerecord-session_store'
gem 'annotate', '~> 2.6.6'
gem 'apipie-rails', github: 'owahab/apipie-rails'
gem 'bcrypt-ruby'
gem 'cancancan'
gem 'coffee-rails'
gem 'data_uri'
gem 'delayed_paperclip'
gem 'devise', '~> 3.5.1'
gem 'roo'
gem 'paranoia', '~> 2.1.3'
gem 'devise_token_auth', '0.1.31'
gem 'execjs'
gem 'certified'
gem 'jbuilder'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'mechanize'
gem 'turbolinks'
gem 'kaminari'
gem 'pry'
gem 'pry-doc'
gem 'puma'
gem 'libv8'
gem 'mail_view'
gem 'newrelic_rpm'
gem 'paperclip'
gem 'method_source'
gem 'paperclip-av-transcoder'
gem 'pg'
gem 'postmark-rails'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '4.2.1'
gem 'rails_admin'
gem 'resque'
gem 'resque_mailer'
gem 'resque-scheduler'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sass-rails'
gem 'unicorn'
gem 'uglifier'
gem 'state_machine', github: 'seuros/state_machine'
gem 'eventmachine'
gem 'faye'
gem 'rubyzip'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'


group :development, :test do
  gem 'byebug'
  gem 'database_cleaner', require: false
  gem 'factory_girl_rails'
  gem 'foreman'
  gem 'letter_opener'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'spring'
  gem 'web-console', '~> 2.0'
  gem 'codeclimate-test-reporter', require: nil
end

group :production do  
  gem 'rails_12factor'
end


